CREATE DATABASE IF NOT EXISTS nextview;
USE nextview;

CREATE TABLE IF NOT EXISTS Empresa (
  idEmpresa INT PRIMARY KEY AUTO_INCREMENT,
  nomeEmpresa VARCHAR(50) NOT NULL,
  emailEmpresa VARCHAR(50) NOT NULL,
  cnpjEmpresa VARCHAR(14) UNIQUE NOT NULL,
  telefoneEmpresa VARCHAR(14) NOT NULL,
  senhaEmpresa VARCHAR(128) NOT NULL
);
CREATE TABLE IF NOT EXISTS Contato (
    idContato INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    nomeContato VARCHAR(50) NOT NULL,
    emailContato VARCHAR(50) NOT NULL,
    mensagemContato VARCHAR(255) NOT NULL,
    telefoneContato VARCHAR(14) NOT NULL
);


CREATE TABLE Log IF NOT EXISTS(

idLog INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
dtLog DATETIME NOT NULL,
descLog VARCHAR(255) NOT NULL,
qtdErro INT NOT NULL,
tipo VARCHAR(50)
);


CREATE TABLE Conteudo IF NOT EXISTS(

idConteudo INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
tipoConteudo VARCHAR(8) NOT NULL,
CONSTRAINT checktipo CHECK (tipoConteudo IN('Movie', 'TV Show')),
tituloConteudo VARCHAR(255) NOT NULL,
diretorConteudo VARCHAR(255) NOT NULL,
atoresConteudo VARCHAR(255) NOT NULL,
dtLancamentoCont DATE NOT NULL,
generosConteudo VARCHAR(255) NOT NULL,
notaConteudo DECIMAL(5,2) NOT NULL,
sinopseCont VARCHAR(255) NOT NULL,
numVotosCont INT NOT NULL


);

CREATE TABLE ConteudosFavoritos IF NOT EXISTS(

idContFavoritos INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
fkEmpresa INT NOT NULL,
fkConteudo INT NOT NULL,
CONSTRAINT ConsfkEmpresa FOREIGN KEY (fkEmpresa) REFERENCES Empresa(idEmpresa),
CONSTRAINT ConsfkConteudo FOREIGN KEY (fkConteudo) REFERENCES Conteudo(idConteudo)

);